### PR TITLE
Login page#4

### PR DESCRIPTION
**Pull request by ri-dev-git**
added frontend with rainbow toolkit integrated authentication,

### CODE REVIEW

**Comment by ri-dev-git** [comment]
Hi @pavankpdev! Please review the code!:)

**Comment by pavankpdev** [comment]
Hey @ri-dev-git Seems like there are couple of issues with the UI. 

- Button styles do not match the designs from figma.
- Uneven spacing throughout the UI.
- Image deck on the right lacks appropriate spacing for screen size `1024`.
- Image deck should not be displayed on medium/tablet devices.

Although I feel like I should create a simple setup. Like a bare bone auth and rainbow kit setup so that it's easier for you guys to build UI on top of it, let me create an issue build it.

**Comment by ri-dev-git** [comment]
ok @pavankpdev! i will do the changes and commit them thanks for the review!

**Comment by pavankpdev** [comment]
Hey @ri-dev-git I've made a global setup of rainbow auth and auth pages, since two different people are working on auth module, there was a lot of merge conflicts and inconsistent setup.

**Pull request closed without merging**
