### PR TITLE
Registration page added

### PR DESCRIPTION
**Pull request by Harshalyadav**

### CODE REVIEW

**Comment by pavankpdev** [comment]
@Harshalyadav can you resolve these merge conflicts

**Comment by pavankpdev** [comment]
Hey @Harshalyadav This PR needs some improvements. The layouts are not setup properly, and responsiveness breaks. Please contact us on discord if you need further assistance. 

Check this video for further clarifications
[Click here for the Video](https://duolearn-public.s3.ap-south-1.amazonaws.com/Screen+Recording+2023-05-19+at+2.14.45+PM.mov)

**Comment by Harshalyadav** [comment]
ok, I solve this problem.

**Comment by pavankpdev** [comment]
@Harshalyadav status on this PR?

**Comment by Harshalyadav** [comment]
I pushed my code.
[making responsive](https://github.com/DuolearnHQ/ArtPlace/pull/28/commits/e5fb9147f0e51b919a054334af66e7c87b242e5f)
my commit message.

**Comment by pavankpdev** [comment]
Can you fix this merge conflict as well @Harshalyadav

**Comment by pavankpdev** [comment]
@Harshalyadav any update on this?

**Comment by Harshalyadav** [comment]
sorry, I fix this merge conflict.

**Pull request closed without merging**
